---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Get Lowercase Registry Owner
        id: registry-owner
        run: echo "lowercase=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_OUTPUT"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker Metadata
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ steps.registry-owner.outputs.lowercase }}/lostcityrs-server
          tags: |
            type=sha,prefix=
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and Push Image
        id: push
        uses: docker/bake-action@82490499d2e5613fcead7e128237ef0b0ea210f7 # v7.0.0
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file-tags }}
            ${{ steps.meta.outputs.bake-file-labels }}
            ${{ steps.meta.outputs.bake-file-annotations }}
          set: |
            image.output=type=image,push=true,compression=zstd
            image.platform=linux/amd64,linux/arm64
            image.cache-from=type=gha
            image.cache-to=type=gha,mode=max
          targets: image
          source: .

      - name: Get Image Digest
        id: digest
        run: |
          DIGEST=$(docker buildx imagetools inspect ${{ env.IMAGE_REGISTRY }}/${{ steps.registry-owner.outputs.lowercase }}/lostcityrs-server:latest --format '{{ json . }}' | jq -r '.manifest.digest')
          echo "digest=${DIGEST}" >> "$GITHUB_OUTPUT"

      - name: Generate Artifact Attestation
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
        with:
          subject-name: ${{ env.IMAGE_REGISTRY }}/${{ steps.registry-owner.outputs.lowercase }}/lostcityrs-server
          subject-digest: ${{ steps.digest.outputs.digest }}
          push-to-registry: true
